version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
  #  pre_build:
  #    commands:
  #      - echo "pre_build step"
  build:
    commands:
      - aws s3 sync --delete src/ "s3://${website_bucket}"
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution ${cloudfront_id} --paths "/*"
